version: "3.7"
services:

  mysql_db_service:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    command: --log_error_verbosity=2   # errors and warnings
    environment:
      MYSQL_DATABASE: cmms_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: apps
      MYSQL_PASSWORD: medos2023
    #      MYSQL_ALLOW_EMPTY_PASSWORD: false
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  web_cmms:
    build: .
    restart: always
    ports:
      - "8881:8080"
    depends_on:
      - mysql_db_service
    volumes:
      - /home/images:/home/images
    networks:
      - mynetwork

  backup:
    image: mysql:latest
    volumes:
      - /home/backups:/backup
    depends_on:
      - mysql_db_service
    networks:
      - mynetwork
    entrypoint:
      - /bin/bash
      - -c
      - |
        bash -c 'while true; do mysqldump -h mysql_db_service -uroot -proot --all-databases > /backup/dump.sql; sleep 300; done'
        
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    depends_on:
      - mysql_db_service
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:

