version: "3.7"
services:

  mysql_db_service:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    command: --log_error_verbosity=2   # errors and warnings
    environment:
      MYSQL_DATABASE: cmms_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: apps
      MYSQL_PASSWORD: medos2023
    #      MYSQL_ALLOW_EMPTY_PASSWORD: false
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  web_cmms:
    build: .
    restart: always
    ports:
      - "8881:8080"
    depends_on:
      - mysql_db_service
    volumes:
      - /home/images:/home/images
    networks:
      - mynetwork

  backup:
    image: mysql:latest
    volumes:
      - /home/backups:/backup
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    depends_on:
      - mysql_db_service
    networks:
      - mynetwork

    entrypoint:
      - /bin/bash
      - -c
      - |
        count=1
        while true; do
           file_name="/backup/dump_`date +%Y_%m_%d__%H_%M`_${count}.sql.gz"
           mysqldump -h mysql_db_service -uroot -proot --all-databases \
           | gzip > $$file_name
           echo "Backup file $$file_name has been generated."
           count=`expr $$count + 1`
           sleep 180
        done

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql_db_service
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    links:
      - mysql_db_service
    networks:
      - mynetwork
    depends_on:
      - mysql_db_service

networks:
  mynetwork:

volumes:
  db_data:

