version: "3.7"
services:

  mysql_db_service:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    command: --log_error_verbosity=2   # errors and warnings
    environment:
      MYSQL_DATABASE: cmms_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: apps
      MYSQL_PASSWORD: medos2023
    #      MYSQL_ALLOW_EMPTY_PASSWORD: false
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  web_cmms:
    build: .
    restart: always
    ports:
      - "8881:8080"
    depends_on:
      - mysql_db_service
    volumes:
      - /home/images:/home/images
    networks:
      - mynetwork

  backup:
    image: mysql:latest
    volumes:
      - /home/backups:/backup
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    depends_on:
      - mysql_db_service
    networks:
      - mynetwork
    entrypoint:
      - /bin/bash
      - -c
      - |
        count=0
        while true; do
          current_hour=$(date +%H)
          target_hour="18"
          if [ "$current_hour" == "$target_hour" ]; then
            timestamp=$(date +%Y%m%d%H%M%S)
            mysqldump -h mysql_db_service -uroot -proot --all-databases \
            | gzip > /backup/dump_${timestamp}_$((count++)).sql.gz
            sleep 86400
         else
           if [ $count -eq 0 ]; then
             timestamp=$(date +%Y%m%d%H%M%S)
             mysqldump -h mysql_db_service -uroot -proot --all-databases \
             | gzip > /backup/dump_${timestamp}_$((count++)).sql.gz
           else
             mysqldump -h mysql_db_service -uroot -proot --all-databases \
             | gzip > /backup/dump_${timestamp}_$((count++)).sql.gz
           fi
           sleep 3600
         fi
        done

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql_db_service
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    links:
      - mysql_db_service
    networks:
      - mynetwork
    depends_on:
      - mysql_db_service

networks:
  mynetwork:

volumes:
  db_data:

