version: "3.7"
services:
  mysql_db_service:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: cmms_db
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true

  cmms_api_service:
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql_db_service