package pl.medos.cmmsApi.enums;

public enum Permission {
    AWIZACJE_USER, AWIZACJE_SU, AWIZACJE_ADMIN,
    PRACOWNICY_USER, PRACOWNICY_SU, PRACOWNICY_ADMIN,
    PRZEPUSTKI_USER, PRZEPUSTKI_SU, PRZEPUSTKI_ADMIN,
    DEPARTMENT_USER, DEPARTMENT_SU, DEPARTMENT_ADMIN,
    MECHANICY_USER, MECHANICY_SU, MECHANICY_ADMIN,
    USER, ADMIN
}

